version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-react
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
    networks:
      - df-network
    depends_on:
      - webapp
  webapp:
    build: ./webapp
    container_name: react-app
    restart: always
    networks:
      - df-network
    volumes:
      - "./webapp/nginx/web_default.conf:/etc/nginx/conf.d/default.conf:ro"
    environment: 
      - NODE_ENV=production
    ports:
      - 3000:3000
networks:
    df-network:
      driver: bridge